# Generated by Django 3.0.8 on 2020-07-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('track', models.ManyToManyField(to='album.Track')),
                ('user', models.ManyToManyField(to='account.Account')),
            ],
        ),
    ]
